// Playlists
export const GET_PLAYLISTS = "GET_PLAYLISTS";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const REMOVE_PLAYLIST = "REMOVE_PLAYLIST";
export const ADD_PLAYLIST_FAILED = "ADD_PLAYLIST_FAILED";
export const CLEAR_PLAYLISTS = "CLEAR_PLAYLISTS";
export const OPEN_CHOOSE_PLAYLIST_DIALOG = "OPEN_CHOOSE_PLAYLIST_DIALOG";
export const CLOSE_CHOOSE_PLAYLIST_DIALOG = "CLOSE_CHOOSE_PLAYLIST_DIALOG";

// Errors and messages
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// Auth and user
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RELOAD_USER_LOADING = "RELOAD_USER_LOADING";
export const RELOAD_USER_LOADED = "RELOAD_USER_LOADED";
export const RELOAD_USER_LOADING_FAILED = "RELOAD_USER_LOADING_FAILED";
export const USERNAME_SUCCESSFULLY_CHANGED = "USERNAME_SUCCESSFULLY_CHANGED";
// Drawer (sidebar)
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_DRAWER = "OPEN_DRAWER";

// Albums
export const ALBUMS_LOADING = "ALBUMS_LOADING";
export const ALBUMS_LOADED = "ALBUMS_LOADED";
export const ALBUMS_LOADING_FAILED = "ALBUMS_LOADING_FAILED";
// Home albums
export const HOME_ALBUMS_LOADING = "HOME_ALBUMS_LOADING";
export const HOME_ALBUMS_LOADED = "HOME_ALBUMS_LOADED";
export const HOME_ALBUMS_LOADING_FAILED = "HOME_ALBUMS_LOADING_FAILED";

// Songs
export const SONGS_LOADED = "SONGS_LOADED";
export const SONGS_LOADING = "SONGS_LOADING";
export const SONGS_LOADING_FAILED = "SONGS_LOADING_FAILED";
// Home songs
export const HOME_SONGS_LOADED = "HOME_SONGS_LOADED";
export const HOME_SONGS_LOADING = "HOME_SONGS_LOADING";
export const HOME_SONGS_LOADING_FAILED = "HOME_SONGS_LOADING_FAILED";

// playlists
export const PLAYLISTS_LOADED = "PLAYLISTS_LOADED";
export const PLAYLISTS_LOADING = "PLAYLISTS_LOADING";
export const PLAYLISTS_LOADING_FAILED = "PLAYLISTS_LOADING_FAILED";
export const PLAYLIST_SONGS_LOADED = "PLAYLIST_SONGS_LOADED";
export const PLAYLIST_SONGS_LOADING = "PLAYLIST_SONGS_LOADING";
export const PLAYLIST_SONGS_LOADING_FAILED = "PLAYLIST_SONGS_LOADING_FAILED";
export const USER_PLAYLISTS_LOADED = "USER_PLAYLISTS_LOADED";
export const USER_PLAYLISTS_LOADING = "USER_PLAYLISTS_LOADING";
export const USER_PLAYLISTS_LOADING_FAILED = "USER_PLAYLISTS_LOADING_FAILED";

// Music player
export const PLAY_SONG = "PLAY_SONG";
export const PLAY_SONG_WITHOUT_CHANGING_QUEUE =
  "PLAY_SONG_WITHOUT_CHANGING_QUEUE";
export const PAUSE_SONG = "PAUSE_SONG";
export const UNPAUSE_SONG = "UNPAUSE_SONG";
export const STOP_SONG = "STOP_SONG";
export const PLAY_NEXT = "PLAY_NEXT";
export const PLAY_PREVIOUS = "PLAY_PREVIOUS";
export const ADD_SONGS_TO_QUEUE = "ADD_SONGS_TO_QUEUE";
export const ADD_SONG_TO_QUEUE = "ADD_SONG_TO_QUEUE";
export const REMOVE_SONG_FROM_QUEUE = "REMOVE_SONG_FROM_QUEUE";
export const CLEAR_PLAYER_QUEUE = "CLEAR_PLAYER_QUEUE";
export const SONG_ENDED = "SONG_ENDED";
export const PLAY_GROUP_OF_SONGS = "PLAY_GROUP_OF_SONGS";
export const PLAY_SONG_AND_KEEP_QUEUE = "PLAY_SONG_AND_KEEP_QUEUE";

// Artists
// artists Info
export const ARTISTS_LOADED = "ARTISTS_LOADED";
export const ARTISTS_LOADING = "ARTISTS_LOADING";
export const ARTISTS_LOADING_FAILED = "ARTISTS_LOADING_FAILED";
// artist albums
export const ARTIST_ALBUMS_LOADED = "ARTISTS_ALBUMS_LOADED";
export const ARTIST_ALBUMS_LOADING = "ARTISTS_ALBUMS_LOADING";
export const ARTIST_ALBUMS_LOADING_FAILED = "ARTISTS_ALBUMS_LOADING_FAILED";
// artist songs
export const ARTIST_SONGS_LOADED = "ARTISTS_SONGS_LOADED";
export const ARTIST_SONGS_LOADING = "ARTISTS_SONGS_LOADING";
export const ARTIST_SONGS_LOADING_FAILED = "ARTISTS_SONGS_LOADING_FAILED";
// artist details
export const ARTIST_DETAILS_LOADED = "ARTISTS_DETAILS_LOADED";
export const ARTIST_DETAILS_LOADING = "ARTISTS_DETAILS_LOADING";
export const ARTIST_DETAILS_LOADING_FAILED = "ARTISTS_DETAILS_LOADING_FAILED";

// Recommended
// recommended albums
export const RECOMMENDED_ALBUMS_LOADED = "RECOMMENDED_ALBUMS_LOADED";
export const RECOMMENDED_ALBUMS_LOADING = "RECOMMENDED_ALBUMS_LOADING";
export const RECOMMENDED_ALBUMS_LOADING_FAILED =
  "RECOMMENDED_ALBUMS_LOADING_FAILED";
// recommended songs
export const RECOMMENDED_SONGS_LOADED = "RECOMMENDED_SONGS_LOADED";
export const RECOMMENDED_SONGS_LOADING = "RECOMMENDED_SONGS_LOADING";
export const RECOMMENDED_SONGS_LOADING_FAILED =
  "RECOMMENDED_SONGS_LOADING_FAILED";
// recommended playlists
export const RECOMMENDED_PLAYLISTS_LOADED = "RECOMMENDED_PLAYLISTS_LOADED";
export const RECOMMENDED_PLAYLISTS_LOADING = "RECOMMENDED_PLAYLISTS_LOADING";
export const RECOMMENDED_PLAYLISTS_LOADING_FAILED =
  "RECOMMENDED_PLAYLISTS_LOADING_FAILED";

// Favorite
// favorite albums
export const FAVORITE_ALBUMS_LOADED = "FAVORITE_ALBUMS_LOADED";
export const FAVORITE_ALBUMS_LOADING = "FAVORITE_ALBUMS_LOADING";
export const FAVORITE_ALBUMS_LOADING_FAILED = "FAVORITE_ALBUMS_LOADING_FAILED";
export const ADD_ALBUM_TO_FAVORITES = "ADD_ALBUM_TO_FAVORITES";
export const REMOVE_ALBUM_FROM_FAVORITES = "REMOVE_ALBUM_FROM_FAVORITES";

// favorite songs
export const FAVORITE_SONGS_LOADED = "FAVORITE_SONGS_LOADED";
export const FAVORITE_SONGS_LOADING = "FAVORITE_SONGS_LOADING";
export const FAVORITE_SONGS_LOADING_FAILED = "FAVORITE_SONGS_LOADING_FAILED";
export const ADD_SONG_TO_FAVORITES = "ADD_SONG_TO_FAVORITES";
export const REMOVE_SONG_FROM_FAVORITES = "REMOVE_SONG_FROM_FAVORITES";

// favorite playlists
export const FAVORITE_PLAYLISTS_LOADED = "FAVORITE_PLAYLISTS_LOADED";
export const FAVORITE_PLAYLISTS_LOADING = "FAVORITE_PLAYLISTS_LOADING";
export const FAVORITE_PLAYLISTS_LOADING_FAILED =
  "FAVORITE_PLAYLISTS_LOADING_FAILED";
export const ADD_PLAYLIST_TO_FAVORITES = "ADD_PLAYLIST_TO_FAVORITES";
export const REMOVE_PLAYLIST_FROM_FAVORITES = "REMOVE_PLAYLIST_FROM_FAVORITES";

//history
export const HISTORY_LOADED = "HISTORY_LOADED";
export const HISTORY_LOADING = "HISTORY_LOADING";
export const HISTORY_LOADING_FAILED = "HISTORY_LOADING_FAILED";

// Search
// search albums
export const SEARCH_ALBUMS_LOADED = "SEARCH_ALBUMS_LOADED";
export const SEARCH_ALBUMS_LOADING = "SEARCH_ALBUMS_LOADING";
export const SEARCH_ALBUMS_LOADING_FAILED = "SEARCH_ALBUMS_LOADING_FAILED";
// search songs
export const SEARCH_SONGS_LOADED = "SEARCH_SONGS_LOADED";
export const SEARCH_SONGS_LOADING = "SEARCH_SONGS_LOADING";
export const SEARCH_SONGS_LOADING_FAILED = "SEARCH_SONGS_LOADING_FAILED";
// search playlists
export const SEARCH_PLAYLISTS_LOADED = "SEARCH_PLAYLISTS_LOADED";
export const SEARCH_PLAYLISTS_LOADING = "SEARCH_PLAYLISTS_LOADING";
export const SEARCH_PLAYLISTS_LOADING_FAILED =
  "SEARCH_PLAYLISTS_LOADING_FAILED";
// search artists
export const SEARCH_ARTISTS_LOADED = "SEARCH_ARTISTS_LOADED";
export const SEARCH_ARTISTS_LOADING = "SEARCH_ARTISTS_LOADING";
export const SEARCH_ARTISTS_LOADING_FAILED = "SEARCH_ARTISTS_LOADING_FAILED";
// search commons
export const SEARCH_COMMONS_LOADED = "SEARCH_COMMONS_LOADED";
export const SEARCH_COMMONS_LOADING = "SEARCH_COMMONS_LOADING";
export const SEARCH_COMMONS_LOADING_FAILED = "SEARCH_COMMONS_LOADING_FAILED";

// Genres
export const GENRES_LOADED = "GENRES_LOADED";
export const GENRES_LOADING = "GENRES_LOADING";
export const GENRES_LOADING_FAILED = "GENRES_LOADING_FAILED";
// Genres albums
export const GENRES_ALBUMS_LOADED = "GENRES_ALBUMS_LOADED";
export const GENRES_ALBUMS_LOADING = "GENRES_ALBUMS_LOADING";
export const GENRES_ALBUMS_LOADING_FAILED = "GENRES_ALBUMS_LOADING_FAILED";

// Profile songs
export const PROFILE_SONG_LOADED = "PROFILE_SONG_LOADED";
export const PROFILE_SONG_LOADING = "PROFILE_SONG_LOADING";
export const PROFILE_SONG_LOADING_FAILED = "PROFILE_SONG_LOADING_FAILED";
// Profile
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_LOADING_FAILED = "PROFILE_LOADING_FAILED";

export const PROFILE_ALBUM_LOADED = "PROFILE_ALBUM_LOADED";
export const PROFILE_ALBUM_LOADING = "PROFILE_ALBUM_LOADING";
export const PROFILE_ALBUM_LOADING_FAILED = "PROFILE_ALBUM_LOADING_FAILED";

//Myaccouny changePassword
export const MYACCOUNT_CHANGE_PASSWORD_LOADED =
  "MYACCOUNT_CHANGE_PASSWORD_LOADED";
export const MYACCOUNT_CHANGE_PASSWORD_LOADING =
  "MYACCOUNT_CHANGE_PASSWORD_LOADING";
export const MYACCOUNT_CHANGE_PASSWORD_LOADEDING_FAILED =
  "MYACCOUNT_CHANGE_PASSWORD_FAILED";
// Admin
// get users
export const USERS_LOADED = "USERS_LOADED";
export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOADING_FAILED = "USERS_LOADING_FAILED";
// get roles
export const USER_ROLES_LOADED = "USER_ROLES_LOADED";
export const USER_ROLES_LOADING = "USER_ROLES_LOADING";
export const USER_ROLES_LOADING_FAILED = "USER_ROLES_LOADING_FAILED";

//Statistics
//inscirptions by month
export const INSCRIPTIONS_BY_MONTH_LOADED = "INSCRIPTIONS_BY_MONTH_LOADED";
export const INSCRIPTIONS_BY_MONTH_LOADING = "INSCRIPTIONS_BY_MONTH_LOADING";
export const INSCRIPTIONS_BY_MONTH_LOADING_FAILED =
  "INSCRIPTIONS_BY_MONTH_FAILED";
//inscirptions by year
export const INSCRIPTIONS_BY_YEAR_LOADED = "INSCRIPTIONS_BY_YEAR_LOADED";
export const INSCRIPTIONS_BY_YEAR_LOADING = "INSCRIPTIONS_BY_YEAR_LOADING";
export const INSCRIPTIONS_BY_YEAR_LOADING_FAILED =
  "INSCRIPTIONS_BY_YEAR_FAILED";

//gender stats
export const GENDER_LOADED = "GENDER_LOADED";
export const GENDER_LOADING = "GENDER_LOADING";
export const GENDER_LOADING_FAILED = "GENDER_FAILED";
//role stats
export const ROLE_LOADED = "ROLE_LOADED";
export const ROLE_LOADING = "ROLE_LOADING";
export const ROLE_LOADING_FAILED = "ROLE_FAILED";
//age stats
export const AGE_LOADED = "AGE_LOADED";
export const AGE_LOADING = "AGE_LOADING";
export const AGE_LOADING_FAILED = "AGE_FAILED";
//country stats
export const COUNTRY_LOADED = "COUNTRY_LOADED";
export const COUNTRY_LOADING = "COUNTRY_LOADING";
export const COUNTRY_LOADING_FAILED = "COUNTRY_FAILED";
//listened song stats
export const LISTENED_SONG_LOADED = "LISTENED_SONG_LOADED";
export const LISTENED_SONG_LOADING = "LISTENED_SONG_LOADING";
export const LISTENED_SONG_LOADING_FAILED = "LISTENED_SONG_LOADING_FAILED";
//favorite song stats
export const FAVORITE_SONG_STATS_LOADED = "FAVORITE_SONG_STATS_LOADED";
export const FAVORITE_SONG_STATS_LOADING = "FAVORITE_SONG_STATS_LOADING";
export const FAVORITE_SONG_STATS_LOADING_FAILED =
  "FAVORITE_SONG_STATS_LOADING_FAILED";
//favorite song stats
export const FAVORITE_ALBUM_STATS_LOADED = "FAVORITE_ALBUM_STATS_LOADED";
export const FAVORITE_ALBUM_STATS_LOADING = "FAVORITE_ALBUM_STATS_LOADING";
export const FAVORITE_ALBUM_STATS_LOADING_FAILED =
  "FAVORITE_ALBUM_STATS_LOADING_FAILED";
